export const SERVER_CONNECTED = 'SERVER_CONNECTED';
export const SET_MEETING_ID = 'SET_MEETING_ID';
export const SET_USER_VIDEO = 'SET_USER_VIDEO';
export const SET_PEER_VIDEO = 'SET_PEER_VIDEO';
export const SET_LOCAL_PEER = 'SET_LOCAL_PEER';
export const SET_REMOTE_PEERS = 'SET_REMOTE_PEERS';